properties:
  gitlab:
    url: https://gitlab.com/api/v4
    username: qwerty62806
    token: glpat-AZ6DMekfZ-4LiAxEzLzh
  bitbucket:
    url: https://api.bitbucket.org/2.0/repositories/
    username: qwerty62806
    pass: ATBBJydHH4feKdyJwYYxPw86dTGd5C78D623
    workspace: task_clone
  path_save: C:\Users\Acer\Desktop\main\localGit
